spring:
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  datasource:
    name: tacocloud
    generate-unique-name: false
    url: jdbc:h2:mem:tacocloud
    username: sa
    password:
    driverClassName: org.h2.Driver